name: Investigate Windows images on GitHub

on:
  push:
    branches: ["main"]

jobs:
  win-2019:
    strategy:
      fail-fast: false
    runs-on: windows-2019
    steps:
    - name: 'list chocolatey packages'
      shell: pwsh
      run: |
        choco list --limit-output
    # WinGet is unavailable for this
    # Need to find how https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/main/scripts/Automation.ps1 had this working
    # Stupid link is to main which 404's Grr, link commit sha's not branches
    # - name: 'install winget'
    #   shell: pwsh
    #   run: |
    #     choco install winget-cli
    #     choco install winget.powershell -y --no-progress --params="/core /desktop"
    # - name: 'list winget packages'
    #   shell: pwsh
    #   run: |
    #     winget list --accept-source-agreements
    
  win-latest:
    strategy:
      fail-fast: false
    runs-on: windows-latest # For Linux, use ubuntu-latest
    steps:
    - name: 'list chocolatey packages'
      shell: pwsh
      run: |
        choco list --limit-output
    - name: 'install winget'
      shell: pwsh
      run: |
        choco install winget-cli
        choco install winget.powershell -y --no-progress --params="/core /desktop"
    - name: 'list winget packages'
      shell: pwsh
      run: |
        winget list --accept-source-agreements
